version: '3'
networks:
  pizza-shop.net:
    driver: bridge
services:

  #################
  ###  API PHP  ###
  #################

  # service shop.pizza-shop : api pour la prise de commandes
  shop.pizza-shop:
    image: 'canals/php:8.2'
    env_file:
      - ./shop.env
      - ./.env
    ports:
      - '41215:80'
    volumes:
      - ../shop.pizza-shop/public:/var/www/html
      - ../shop.pizza-shop:/var/www
    working_dir: /var/www/
    networks:
      pizza-shop.net:
        aliases:
          - shop.pizza-shop.local
    depends_on:
      - pizza-shop.commande.db

  # service catalogue.pizza-shop : api pour le catalogue
  catalogue.pizza-shop:
    image: 'canals/php:8.2'
    env_file:
      - ./cat.env
      - ./.env
    ports:
      - '41216:80'
    volumes:
      - ../catalogue.pizza-shop/public:/var/www/html
      - ../catalogue.pizza-shop:/var/www
    working_dir: /var/www/
    networks:
      pizza-shop.net:
        aliases:
          - catalogue.pizza-shop.local
    depends_on:
      - pizza-shop.catalogue.db

  # service api.pizza-shop : api pour l'authentification
  api.pizza-auth:
    image: 'canals/php:8.2'
    env_file:
      - ./auth.env
      - ./.env
    environment:
      - SECRET_KEY=2zejfieo294Jesfjio929I4jjio0012kjii3ki
    ports:
      - '41217:80'
    volumes:
      - ../auth.pizza-shop/public:/var/www/html
      - ../auth.pizza-shop:/var/www
    working_dir: /var/www
    networks:
      pizza-shop.net:
        aliases:
          - auth.pizza-shop.local
    depends_on:
      - pizza-shop.auth.db

  # service gateway.pizza-shop : api gateway
  gateway.pizza-auth:
    image: 'canals/php:8.2'
    env_file:
      - ./.env
    ports:
      - '41218:80'
    volumes:
      - ../gateway.pizza-shop/public:/var/www/html
      - ../gateway.pizza-shop:/var/www
    working_dir: /var/www
    networks:
      pizza-shop.net:
        aliases:
          - gateway.pizza-shop.local

  #############
  ###  BDD  ###
  #############

  # service sql pour le stockage des commandes
  pizza-shop.commande.db:
    image: 'mariadb:latest'
    command: '--default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci'
    env_file:
      - ./shop.env
      - ./.env
    ports:
      - '41219:3306'
    networks:
      - pizza-shop.net
    volumes:
      - ../shop.pizza-shop/sql:/var/sql

  # service sql pour le catalogue des pizzas
  pizza-shop.catalogue.db:
    image: 'postgres:latest'
    env_file:
      - ./cat.env
      - ./.env
    ports:
      - '41220:5432'
    networks:
      - pizza-shop.net
    volumes:
      - ../catalogue.pizza-shop/sql:/var/sql'

  # service sql pour l'authentification
  pizza-shop.auth.db:
    image: 'mariadb:latest'
    command: '--default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci'
    env_file:
      - ./auth.env
      - ./.env
    ports:
      - '41221:3306'
    networks:
      - pizza-shop.net
    volumes:
      - ../auth.pizza-shop/sql:/var/sql

  #################
  ###  ADMINER  ###
  #################

  # service administration des bases sql
  adminer:
    image: adminer
    command: php -S 0.0.0.0:8080 -t /var/www/html
    ports:
      - '41222:8080'
    networks:
      - pizza-shop.net

  #################
  ###  RABITMQ  ###
  #################
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '15672:15672'
      - '5672:5672'
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 8s
      timeout: 30s
      retries: 3
    networks:
      - pizza-shop.net
    volumes:
      - ../rabbitmq.pizza-shop:/var/lib/rabbitmq
    env_file: ./rab.env

  rabbit.php:
    image: 'canals/php:8.2'
    ports:
      - '15673:80'
    volumes:
      - ../rabbitmq.pizza-shop/data:/var/lib/rabbitmq
      - ../rabbitmq.pizza-shop:/var/www
    working_dir: /var/www/
    networks:
      - pizza-shop.net
    env_file: ./rab.env

  ####################
  ###  EXPRESS JS  ###
  ####################

  api.service:
    image: node:alpine
    networks:
      - pizza-shop.net
    working_dir: /usr/app
    command: sh -c "npm i && npm run watch"
    volumes:
      - ../express.pizza-shop/service-dir:/usr/app
    ports:
      - '3333:3000'
    environment:
      PORT: 3000
      NODE_ENV: development